<Project>
  <PropertyGroup>
    <AssemblyVersion>26.10.6</AssemblyVersion>
    <FileVersion>26.10.6</FileVersion>
    <Version>26.10.6</Version>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Company>TownSuite Municipal Software Inc.</Company>
    <Product>TownSuite Code Signing</Product>
    <Copyright>Copyright © TownSuite Municipal Software Inc. 2026</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugSymbols>False</DebugSymbols>
    <DebugType>None</DebugType>
  </PropertyGroup>
</Project>
